# Generated by Django 4.2.7 on 2023-12-17 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simpleapp', '0003_rename_new_news'),
    ]

    operations = [
        migrations.DeleteModel(
            name='News',
        ),
    ]
