# Generated by Django 4.2.7 on 2023-12-19 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simpleapp', '0006_product_material'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='material',
        ),
    ]
