# Generated by Django 4.2.7 on 2023-12-19 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simpleapp', '0011_remove_product_material_product_product_material'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='choice',
            field=models.CharField(choices=[('sport', 'спорт'), ('thing_for_home', 'вещи для дома')], default='sport', max_length=20),
        ),
    ]
