# Generated by Django 4.2.7 on 2023-12-19 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simpleapp', '0012_product_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='choice',
            field=models.CharField(choices=[('кожа', 'кожа'), ('волокно', 'волокно')], default='кожа', max_length=20),
        ),
    ]
