# Generated by Django 4.2.7 on 2023-12-19 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simpleapp', '0015_product_material'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='material',
        ),
        migrations.AddField(
            model_name='product',
            name='choice',
            field=models.CharField(choices=[('кожа', 'кожа'), ('волокно', 'волокно')], default='кожа', max_length=20),
        ),
    ]
