# Generated by Django 4.2.7 on 2023-12-30 04:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=120)),
                ('message', models.TextField()),
                ('date', models.DateField(default=datetime.datetime.utcnow)),
            ],
        ),
    ]
