# Generated by Django 4.2.7 on 2023-12-16 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155)),
                ('description', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='new',
            name='description',
        ),
        migrations.AlterField(
            model_name='new',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
