# Generated by Django 4.2.7 on 2023-12-17 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_news_remove_new_description_alter_new_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='New',
        ),
    ]
