# Generated by Django 4.2.7 on 2023-12-24 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_news_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='type',
        ),
        migrations.AddField(
            model_name='news',
            name='article_news',
            field=models.CharField(choices=[('NW', 'новость'), ('AR', 'статья')], default='NW', max_length=2),
        ),
    ]
